# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr

class OwnPassword(BaseModel):
    """
    OwnPassword
    """
    old_password: StrictStr = Field(...)
    password: StrictStr = Field(...)
    __properties = ["old_password", "password"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> OwnPassword:
        """Create an instance of OwnPassword from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> OwnPassword:
        """Create an instance of OwnPassword from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return OwnPassword.parse_obj(obj)

        _obj = OwnPassword.parse_obj({
            "old_password": obj.get("old_password"),
            "password": obj.get("password")
        })
        return _obj


