name: Build Python API Client
description: 'Build Python Client for a service'

inputs:
  image-name:
    description: Docker image name (service_name:label)
    required: false
    default: 'quay.io/rapyuta/io_amr_gwm:api-client-testing'

runs:
  using: composite
  steps:
    - name: Get Service Docker
      uses: addnab/docker-run-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: quay.io
        image: ${{ inputs.image-name }}
        run:
          - 