name: Build Python API Client
description: 'Build Python Client for a service'

inputs:
  image-name:
    description: Docker image name (service_name:label)
    required: false
    default: 'quay.io/rapyuta/io_amr_gwm:api-client-testing'
  quay-username:
    description: Quay.io username
    required: true
  quay-password:
    description: Quay.io password
    required: true

runs:
  using: composite
  services:
    services:
      docker:
        image: docker:20.10.8-dind
        options: --privileged
        ports:
          - 2375:2375
  steps:
    - name: Docker Login to Quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{inputs.quay-username}}
        password: ${{inputs.quay-password}}

    - name: Run Docker Service
      run: |
        # Start your Docker service container here, pulling from your private registry
        docker pull ${{inputs.image-name}}
        docker run -d --network host ${{inputs.image-name}} poetry run gunicorn
    - name: TEST
      run: |
        # OK
        curl localhost:8000