# coding: utf-8

"""
    IO-AMR GWM API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: devel
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt, StrictStr, validator

class AssetLocationLocationRequest(BaseModel):
    """
    TODO: support thing other than spot, merge with libs.location  # noqa: E501
    """
    type: StrictStr = Field(..., description="* `spot` - Spot * `spot_query` - Spot Query")
    id: StrictInt = Field(...)
    __properties = ["type", "id"]

    @validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('spot', 'spot_query'):
            raise ValueError("must be one of enum values ('spot', 'spot_query')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AssetLocationLocationRequest:
        """Create an instance of AssetLocationLocationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AssetLocationLocationRequest:
        """Create an instance of AssetLocationLocationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AssetLocationLocationRequest.parse_obj(obj)

        _obj = AssetLocationLocationRequest.parse_obj({
            "type": obj.get("type"),
            "id": obj.get("id")
        })
        return _obj


