# flake8: noqa

# import apis into api package
from io_amr_gwm.api.containers_app_asset_location_api import ContainersAppAssetLocationApi
from io_amr_gwm.api.containers_app_container_descriptor_api import ContainersAppContainerDescriptorApi
from io_amr_gwm.api.containers_app_container_master_api import ContainersAppContainerMasterApi
from io_amr_gwm.api.containers_app_product_api import ContainersAppProductApi
from io_amr_gwm.api.errors_app_error_actions_api import ErrorsAppErrorActionsApi
from io_amr_gwm.api.errors_app_error_types_api import ErrorsAppErrorTypesApi
from io_amr_gwm.api.graph_generator_graph_api import GraphGeneratorGraphApi
from io_amr_gwm.api.graph_generator_locations_api import GraphGeneratorLocationsApi
from io_amr_gwm.api.graph_generator_regions_api import GraphGeneratorRegionsApi
from io_amr_gwm.api.maps_app_edges_api import MapsAppEdgesApi
from io_amr_gwm.api.maps_app_layers_api import MapsAppLayersApi
from io_amr_gwm.api.maps_app_maps_api import MapsAppMapsApi
from io_amr_gwm.api.maps_app_nodes_api import MapsAppNodesApi
from io_amr_gwm.api.maps_app_regions_api import MapsAppRegionsApi
from io_amr_gwm.api.maps_app_spots_api import MapsAppSpotsApi
from io_amr_gwm.api.robots_app_agents_api import RobotsAppAgentsApi
from io_amr_gwm.api.robots_app_robot_descriptors_api import RobotsAppRobotDescriptorsApi
from io_amr_gwm.api.robots_app_robots_api import RobotsAppRobotsApi
from io_amr_gwm.api.sites_app_external_devices_api import SitesAppExternalDevicesApi
from io_amr_gwm.api.sites_app_schemas_api import SitesAppSchemasApi
from io_amr_gwm.api.sites_app_sites_api import SitesAppSitesApi
from io_amr_gwm.api.works_app_agent_task_fragments_api import WorksAppAgentTaskFragmentsApi
from io_amr_gwm.api.works_app_agent_tasks_api import WorksAppAgentTasksApi
from io_amr_gwm.api.works_app_work_fragments_v2_api import WorksAppWorkFragmentsV2Api
from io_amr_gwm.api.works_app_work_fragments_v3_api import WorksAppWorkFragmentsV3Api
from io_amr_gwm.api.works_app_works_v2_api import WorksAppWorksV2Api
from io_amr_gwm.api.works_app_works_v3_api import WorksAppWorksV3Api

