# coding: utf-8

"""
    IO-AMR GWM API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: devel
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, StrictStr, validator
from gwm_client.models.pos import Pos

class Location(BaseModel):
    """
    Location
    """
    type: Optional[StrictStr] = Field('spot_query', description="* `spot` - Spot * `spot_query` - Spot Query * `region` - Region * `pos` - Pos")
    spot_query: Optional[Dict[str, Any]] = None
    spot: Optional[Dict[str, Any]] = None
    region: Optional[Dict[str, Any]] = None
    pos: Optional[Pos] = None
    __properties = ["type", "spot_query", "spot", "region", "pos"]

    @validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('spot', 'spot_query', 'region', 'pos'):
            raise ValueError("must be one of enum values ('spot', 'spot_query', 'region', 'pos')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Location:
        """Create an instance of Location from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of pos
        if self.pos:
            _dict['pos'] = self.pos.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Location:
        """Create an instance of Location from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Location.parse_obj(obj)

        _obj = Location.parse_obj({
            "type": obj.get("type") if obj.get("type") is not None else 'spot_query',
            "spot_query": obj.get("spot_query"),
            "spot": obj.get("spot"),
            "region": obj.get("region"),
            "pos": Pos.from_dict(obj.get("pos")) if obj.get("pos") is not None else None
        })
        return _obj


