# coding: utf-8

"""
    IO-AMR GWM API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: api-client-testing
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, conlist, constr, validator

class Polygon(BaseModel):
    """
    GIS Polygon - (representation of polygon with 1 or more LinearRings)  # noqa: E501
    """
    type: Optional[constr(strict=True)] = 'Polygon'
    coordinates: conlist(conlist(conlist(Union[StrictFloat, StrictInt], max_items=2, min_items=2), min_items=4), min_items=1) = Field(...)
    __properties = ["type", "coordinates"]

    @validator('type')
    def type_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"Polygon", value):
            raise ValueError(r"must validate the regular expression /Polygon/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Polygon:
        """Create an instance of Polygon from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Polygon:
        """Create an instance of Polygon from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Polygon.parse_obj(obj)

        _obj = Polygon.parse_obj({
            "type": obj.get("type") if obj.get("type") is not None else 'Polygon',
            "coordinates": obj.get("coordinates")
        })
        return _obj


