name: Workflow Caller
on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: rapyuta-robotics
          repo: rr_api_clients
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_user: tharindurr
          workflow_file_name: build.yaml
          ref: devel
          wait_interval: 10
          client_payload: '{
            "docker-image-name": "quay.io/rapyuta/io_amr_gwm",
            "client-name": "gwm",
            "version": "api-client-testing",
            "service-port": "8000",
            "openapi-path": "api/schema/",
            "docker-command": "poetry run gunicorn"
          }'
          propagate_failure: false
          trigger_workflow: true
          wait_workflow: true